# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'

language: R
cache: packages
sudo: false

# Follow the ropenscilabs travis.yml
stages:
- name: test
- name: full
  if: branch = master

#jobs: 4x Linux (1x with deployment), 1x OSX
jobs:
  include:
  - stage: test
    r: devel
  - stage: full
    r: release
    env:
    - BUILD_PKGDOWN=true
  - os: osx
    r: release
    env:
      - BUILD_PKGDOWN=true
  - r: 3.5
  - r: 3.4
  - r: 3.3

matrix:
    fast_finish: true
